export type SpecAreaId = 'business' | 'frontend'
export type DeviceKind = 'pixel' | 'iphone'

export interface SpecPrinciple {
  id: string
  number: number
  title: string
  eyebrow: string
  summary: string
  rules: string[]
  recommend: string
  avoid: string
  sceneId: string
  checkpoints: string[]
}

export interface SpecArea {
  id: SpecAreaId
  index: string
  title: string
  shortTitle: string
  description: string
  principles: SpecPrinciple[]
}

export const businessPrinciples: SpecPrinciple[] = [
  {
    id: 'role-task',
    number: 1,
    eyebrow: 'ROLE & TASK',
    title: '角色与任务优先',
    summary: '移动首页应回答“我现在需要处理什么”，而不是复制后台系统的全部模块。巡检、值班和管理角色共用结构，但默认内容与排序不同。',
    rules: [
      '首页优先展示待处理、临期和异常任务。',
      '角色差异通过内容排序和默认视图表达，不复制三套组件。',
      '每个任务直接提供状态、对象、时限与下一步动作。',
    ],
    recommend: '巡检人员首屏看到今日任务、附近设施和待同步记录。',
    avoid: '所有角色进入同一九宫格，再逐层寻找所属业务模块。',
    sceneId: 'role-task',
    checkpoints: ['首屏出现当前待办', '任务提供直接动作', '切换角色后结构保持稳定'],
  },
  {
    id: 'priority',
    number: 2,
    eyebrow: 'PRIORITY',
    title: '当前任务优先',
    summary: '高频工作流优先呈现正在发生的事件、处理中任务与下一步，完整功能目录退居二级入口。',
    rules: [
      '按紧急程度、时限和责任关系排序。',
      '首屏只保留一个明确主任务区。',
      '功能入口不与任务卡片争夺视觉主次。',
    ],
    recommend: '将超时巡检和水位越线置顶，并给出“继续处置”。',
    avoid: '用完整组织树、报表目录和系统配置占满首屏。',
    sceneId: 'priority',
    checkpoints: ['异常优先于常规项', '下一步动作可直接触达', '功能目录处于次级'],
  },
  {
    id: 'trustworthy-data',
    number: 3,
    eyebrow: 'DATA TRUST',
    title: '数据可信表达',
    summary: '水位、雨量、流量和设备状态必须同时说明数值含义、来源与新鲜度，避免用户基于过期数据做判断。',
    rules: [
      '数值必须伴随单位、测站与更新时间。',
      '显示正常、超限、离线、故障或估算等质量状态。',
      '缓存数据与实时数据使用明确文本区分。',
    ],
    recommend: '显示“28.46 m · 南门水库 · 2 分钟前 · 遥测正常”。',
    avoid: '只用绿色大数字“28.46”，不说明单位和采集时间。',
    sceneId: 'trustworthy-data',
    checkpoints: ['单位不依赖上下文猜测', '更新时间可见', '过期状态不使用正常绿色'],
  },
  {
    id: 'state-first',
    number: 4,
    eyebrow: 'STATE FIRST',
    title: '状态优先于装饰',
    summary: '监测界面应先让用户识别异常、影响、责任人与处置进度，再展示趋势和品牌装饰。',
    rules: [
      '异常状态在标题和摘要层直接表达。',
      '状态同时使用文字、图形和色彩。',
      '装饰性图表不得遮蔽业务结论。',
    ],
    recommend: '事件卡首行显示“闸门反馈异常”，随后给出影响与责任人。',
    avoid: '使用大面积发光图形和科技背景，却把异常放在角落。',
    sceneId: 'state-first',
    checkpoints: ['三秒内可识别异常', '状态不只靠颜色', '责任和进度可见'],
  },
  {
    id: 'field-operation',
    number: 5,
    eyebrow: 'FIELD READY',
    title: '现场可操作',
    summary: '现场可能存在强光、雨水、手套与单手握持，核心操作必须拥有更大热区并靠近自然触达区。',
    rules: [
      '现场主按钮高度建议 52 至 56px。',
      '危险操作与普通操作保持清晰间距。',
      '顶部图标不得成为核心动作唯一入口。',
    ],
    recommend: '在底部提供全宽“开始检查”，定位和扫码使用大热区按钮。',
    avoid: '在右上角排列多个 20px 图标要求现场人员精确点击。',
    sceneId: 'field-operation',
    checkpoints: ['主动作单手可达', '图标具备完整热区', '危险操作位置独立'],
  },
  {
    id: 'assisted-input',
    number: 6,
    eyebrow: 'ASSISTED INPUT',
    title: '采集代替重复录入',
    summary: '利用扫码、定位、拍照、语音和任务上下文自动填充可确认信息，把键盘输入留给必须由人员判断的内容。',
    rules: [
      '自动带入人员、时间、对象和任务编号。',
      '自动识别结果必须允许核验与修正。',
      '采集入口与表单字段建立清晰对应关系。',
    ],
    recommend: '扫码识别设备后自动填充站点，用户补充异常描述与照片。',
    avoid: '要求用户逐项输入已有的设备编码、位置、部门和人员信息。',
    sceneId: 'assisted-input',
    checkpoints: ['自动值可核验', '采集结果回填明确', '手工字段数量显著减少'],
  },
  {
    id: 'offline',
    number: 7,
    eyebrow: 'OFFLINE FIRST',
    title: '离线是完整工作模式',
    summary: '弱网或断网时允许继续查看任务、填写记录和采集附件，并准确区分本地保存与服务端确认。',
    rules: [
      '统一使用本地草稿、等待同步、同步中、已确认状态。',
      '同步失败保留全部输入和附件。',
      '生产控制指令禁止离线排队。',
    ],
    recommend: '断网时显示“已保存到本机，3 项等待同步”并提供队列入口。',
    avoid: '断网后禁用整页，或把本地保存提示为“提交成功”。',
    sceneId: 'offline',
    checkpoints: ['网络状态持续可见', '本地与服务端状态分离', '失败可以逐项重试'],
  },
  {
    id: 'alarm',
    number: 8,
    eyebrow: 'ALARM FLOW',
    title: '告警具有完整生命周期',
    summary: '告警是需要确认、处置、恢复和关闭的业务对象，推送和 Toast 只负责引导用户进入告警。',
    rules: [
      '明确区分已送达、已确认、处置中、已恢复和已关闭。',
      '显示等级、对象、时间、当前值、阈值和影响范围。',
      '确认收到与确认解决必须是两个动作。',
    ],
    recommend: '告警详情展示持续时间线，并提供“确认并开始处置”。',
    avoid: '只弹出一次红色 Toast，消失后没有记录和下一步。',
    sceneId: 'alarm',
    checkpoints: ['告警状态可持续追踪', '等级不只靠颜色', '确认与关闭语义不同'],
  },
  {
    id: 'truthful-feedback',
    number: 9,
    eyebrow: 'TRUE FEEDBACK',
    title: '反馈对应真实过程',
    summary: '点击、平台受理、指令下发和设备执行是不同阶段，界面不得提前把技术响应包装成业务成功。',
    rules: [
      '分别显示请求已发送、平台已受理和设备已回执。',
      '超时使用“结果未知”，避免误导用户重复操作。',
      '最终成功依赖有效业务回执。',
    ],
    recommend: '用四阶段进度明确展示闸门指令从校验到遥信确认。',
    avoid: '接口返回 200 后立即显示“闸门已开启”。',
    sceneId: 'truthful-feedback',
    checkpoints: ['反馈阶段与真实状态一致', '超时不等于失败', '最终回执来源明确'],
  },
  {
    id: 'high-risk',
    number: 10,
    eyebrow: 'RISK CONTROL',
    title: '高风险操作提高摩擦',
    summary: '闸泵控制、阈值修改和调度参数下发必须通过实时状态检查、摘要确认和身份复核降低误操作风险。',
    rules: [
      '展示对象、动作、目标值、影响范围和数据时间。',
      '只允许在线执行，并进行二次身份确认。',
      '高危场景支持双人复核或审批。',
    ],
    recommend: '先展示执行摘要，再要求复核身份，最后等待设备回执。',
    avoid: '在设备列表中提供无摘要的一键启停开关。',
    sceneId: 'high-risk',
    checkpoints: ['实时状态可见', '动作与对象再次确认', '发送成功与执行成功分离'],
  },
  {
    id: 'recovery',
    number: 11,
    eyebrow: 'RECOVERY',
    title: '失败可恢复，冲突可理解',
    summary: '网络与并发修改不应让用户丢失现场成果，关键冲突必须展示差异并由用户选择。',
    rules: [
      '失败后保留字段、附件和滚动位置。',
      '关键数据冲突禁止简单最后写入覆盖。',
      '错误提示同时说明影响和下一步。',
    ],
    recommend: '并列显示本机与服务端版本，突出冲突字段并允许选择。',
    avoid: '保存失败后清空表单，或静默覆盖他人刚更新的数据。',
    sceneId: 'recovery',
    checkpoints: ['输入不会丢失', '冲突字段可比较', '恢复动作明确'],
  },
  {
    id: 'audit',
    number: 12,
    eyebrow: 'AUDIT TRAIL',
    title: '过程可追溯并可续接',
    summary: '跨端与跨角色协作必须保留完整时间线，让用户知道谁在何时以什么依据执行了什么动作。',
    rules: [
      '记录操作者、时间、对象、参数和结果。',
      '从主应用进入垂类业务时传递任务上下文。',
      '返回后恢复列表条件和原处理位置。',
    ],
    recommend: '事件详情提供操作时间线，可展开查看审批与设备回执。',
    avoid: '历史记录只有“已完成”，没有执行人、目标值和结果来源。',
    sceneId: 'audit',
    checkpoints: ['责任链完整', '关键参数可复核', '跨端返回不丢上下文'],
  },
]

export const frontendPrinciples: SpecPrinciple[] = [
  {
    id: 'responsive',
    number: 1,
    eyebrow: 'RESPONSIVE',
    title: '移动端重新编排',
    summary: '移动端不是缩小的 PC 页面。手机使用单列任务流，大屏与折叠屏在空间允许时升级为列表详情双栏。',
    rules: [
      '按可用宽度而不是设备型号设计。',
      '禁止随视口等比缩放字体和触控区。',
      '核心内容不依赖横向页面滚动。',
    ],
    recommend: '手机显示摘要列表，宽屏展开关联详情。',
    avoid: '把桌面表格和侧栏整体缩小塞入 375px 视口。',
    sceneId: 'responsive',
    checkpoints: ['手机无页面横向滚动', '内容优先级保持一致', '宽屏合理利用空间'],
  },
  {
    id: 'stable-shell',
    number: 2,
    eyebrow: 'PAGE SHELL',
    title: '页面骨架稳定',
    summary: '标题、上下文、内容区和主操作位置在加载与刷新过程中保持稳定，避免用户刚准备点击时界面跳动。',
    rules: [
      '骨架屏结构与最终内容一致。',
      '局部刷新保留已有内容。',
      '固定操作栏预留安全区域和内容间距。',
    ],
    recommend: '列表刷新时保留行内容，在标题旁显示轻量刷新状态。',
    avoid: '每次请求都清空整页并用居中菊花替代。',
    sceneId: 'stable-shell',
    checkpoints: ['无明显布局位移', '操作区位置不变', '刷新不阻断阅读'],
  },
  {
    id: 'navigation',
    number: 3,
    eyebrow: 'NAVIGATION',
    title: '导航连续可返回',
    summary: '列表、详情与编辑构成连续任务路径，系统返回和页面返回应得到一致且可预测的结果。',
    rules: [
      '返回列表时保留筛选、分页和滚动位置。',
      '有草稿时返回必须自动保存或提示。',
      '主应用与垂类页面明确返回目标。',
    ],
    recommend: '从第三条任务进入详情，返回后仍定位第三条并保留“待处理”筛选。',
    avoid: '任何返回都重建首页，让用户重新查找对象。',
    sceneId: 'navigation',
    checkpoints: ['返回目标可预测', '列表上下文恢复', '未保存内容有保护'],
  },
  {
    id: 'hierarchy',
    number: 4,
    eyebrow: 'HIERARCHY',
    title: '信息分层而非堆叠',
    summary: '列表负责识别与比较，详情负责完整阅读，编辑负责完成任务；同一屏不承担全部信息和全部动作。',
    rules: [
      '列表项限制为标题、状态与 2 至 4 个关键字段。',
      '次要字段进入详情分组。',
      '高级操作通过更多菜单或二级页面提供。',
    ],
    recommend: '列表先显示测站状态和更新时间，点击后查看完整遥测与履历。',
    avoid: '列表行塞入十余字段、图表、按钮和说明文字。',
    sceneId: 'hierarchy',
    checkpoints: ['列表可快速扫描', '详情信息完整', '主次动作有层级'],
  },
  {
    id: 'touch',
    number: 5,
    eyebrow: 'TOUCH',
    title: '触控与手势可发现',
    summary: '所有核心交互拥有足够触控面积；侧滑与长按用于提效，但必须存在显式等价入口。',
    rules: [
      '常规热区至少 44×44，推荐 48px。',
      '相邻危险和普通操作保持间距。',
      '手势操作提供可见按钮或菜单。',
    ],
    recommend: '24px 图标放在 48px 图标按钮中，并提供明确标签或提示。',
    avoid: '使用 16px 文本链接或要求用户猜测侧滑操作。',
    sceneId: 'touch',
    checkpoints: ['热区达标', '操作可发现', '误触后可取消或恢复'],
  },
  {
    id: 'form',
    number: 6,
    eyebrow: 'MOBILE FORM',
    title: '移动表单低摩擦',
    summary: '表单采用单列、标签置顶和语义分组，使用合适键盘与自动填充降低输入负担。',
    rules: [
      '标签位于控件上方，不使用左右挤压布局。',
      '校验错误出现在字段附近并可直接定位。',
      '软键盘弹出后当前字段和提交按钮可操作。',
    ],
    recommend: '数字字段调起数字键盘，失焦后校验并保留用户输入。',
    avoid: '三列并排输入、占位符代替标签、提交后才统一报错。',
    sceneId: 'form',
    checkpoints: ['标签不会消失', '错误与字段对应', '键盘不遮挡当前操作'],
  },
  {
    id: 'ui-states',
    number: 7,
    eyebrow: 'UI STATES',
    title: '状态覆盖完整',
    summary: '加载、空、筛选无结果、失败、无权限、离线和数据过期是不同状态，必须提供不同说明和动作。',
    rules: [
      '空数据与筛选无结果使用不同文案。',
      '错误状态说明数据是否保留。',
      '无权限状态提供申请或返回路径。',
    ],
    recommend: '“当前筛选无结果”同时展示条件和“清除筛选”。',
    avoid: '所有异常统一显示空白页或“暂无数据”。',
    sceneId: 'ui-states',
    checkpoints: ['状态语义准确', '提供可执行下一步', '页面结构保持稳定'],
  },
  {
    id: 'feedback',
    number: 8,
    eyebrow: 'FEEDBACK',
    title: '反馈按影响范围分层',
    summary: '字段、局部、页面和高风险操作使用不同反馈载体，避免 Toast 承担所有信息。',
    rules: [
      '字段错误使用行内反馈。',
      '页面级异常使用持续 Banner。',
      '需要决策或高风险信息使用 Dialog 或确认页。',
    ],
    recommend: '上传失败显示在对应附件行，并提供单项重试。',
    avoid: '连续弹出多个 Toast，用户无法定位对应字段或对象。',
    sceneId: 'feedback',
    checkpoints: ['反馈与对象相邻', '重要信息不会自动消失', '提示包含下一步'],
  },
  {
    id: 'actions',
    number: 9,
    eyebrow: 'ACTION HIERARCHY',
    title: '主次操作明确',
    summary: '每个页面阶段只强调一个最可能的下一步，次要动作降级，危险动作隔离。',
    rules: [
      '每屏最多一个视觉主按钮。',
      '次要动作使用文本、描边或更多菜单。',
      '危险动作不紧贴主提交按钮。',
    ],
    recommend: '详情底部强调“开始处置”，转派和关闭收纳为次操作。',
    avoid: '保存、提交、转派、删除四个按钮使用同等高亮。',
    sceneId: 'actions',
    checkpoints: ['下一步一眼可识别', '次操作仍可发现', '危险动作不会误触'],
  },
  {
    id: 'crud-recovery',
    number: 10,
    eyebrow: 'CRUD RECOVERY',
    title: 'CRUD 可恢复且防重复',
    summary: '新增、编辑和上传在失败时保留成果，正式提交具备幂等与明确状态，删除按风险选择撤销或确认。',
    rules: [
      '长表单自动保存草稿并展示保存时间。',
      '提交中防止重复请求但不清空内容。',
      '上传失败支持逐项重试。',
    ],
    recommend: '提交失败后保留表单和照片，恢复网络后继续上传。',
    avoid: '重复点击生成多条工单，失败后要求从头填写。',
    sceneId: 'crud-recovery',
    checkpoints: ['草稿状态可见', '重复提交被抑制', '失败项可以独立恢复'],
  },
  {
    id: 'data-ui',
    number: 11,
    eyebrow: 'DATA UI',
    title: '数据组件语义完整',
    summary: '图表、指标和列表必须在小屏上保留单位、阈值、时间范围与状态含义，而不是只追求视觉简洁。',
    rules: [
      '图表标题明确对象、指标和时间范围。',
      '阈值线和异常点提供文本说明。',
      '复杂图表提供列表或原始数据入口。',
    ],
    recommend: '水位趋势同时展示警戒线、当前值和最近更新时间。',
    avoid: '只显示无坐标单位的蓝色曲线，依赖用户猜测含义。',
    sceneId: 'data-ui',
    checkpoints: ['单位和时间范围可见', '状态不只靠颜色', '可进入详细数据'],
  },
  {
    id: 'role-density',
    number: 12,
    eyebrow: 'ROLE DENSITY',
    title: '共用体系，轻量适配角色',
    summary: '三类角色共用页面模板与组件，通过默认排序、信息密度和主操作适应不同任务，而不是维护三套设计系统。',
    rules: [
      '巡检模式使用舒适密度和大操作区。',
      '值班模式提高事件列表密度但保持触控热区。',
      '管理模式突出摘要、趋势与钻取。',
    ],
    recommend: '同一任务组件根据角色切换摘要字段和默认动作。',
    avoid: '所有角色使用完全相同首页，或为每类角色复制一套组件。',
    sceneId: 'role-density',
    checkpoints: ['组件语义一致', '角色重点明显', '切换不会改变基础操作逻辑'],
  },
]

export const specAreas: SpecArea[] = [
  {
    id: 'business',
    index: '01',
    title: '产品与业务流程规范',
    shortTitle: '产品业务',
    description: '面向巡检、监测处置与管理决策的移动工作流。',
    principles: businessPrinciples,
  },
  {
    id: 'frontend',
    index: '02',
    title: '前端交互与 UI 体系',
    shortTitle: '前端体系',
    description: '面向首页、布局、列表、表单、CRUD 与状态反馈的工程规范。',
    principles: frontendPrinciples,
  },
]
